// Generated by https://quicktype.io

export interface CalificacionesInstrumentoResponse {
    content:       Calificacion[];
    size:          number;
    totalElements: number;
    pageNumber:    number;
    first:         boolean;
    last:          boolean;
}

export interface Calificacion {
    id:           string;
    calificacion: number;
    referente:    Referente;
    alumno:       Alumno;
}

export interface Alumno {
    id: string;
    nombre: string;
}

export interface Referente {
    codReferente: string;
    descripcion:  string;
}
