// Generated by https://quicktype.io

export interface CreatedAsignaturaResponse {
  id: string;
  asigNombre: string;
  asigDescripcion: string;
  nombreProfesor: string;
  color: string;
  numAlumnos: null;
}
