// Generated by https://quicktype.io

export interface CreatedAlumnoResponse {
    nombre:          string;
    apellido:        string;
    fechaNacimiento: string;
    telefono:        string;
    email:           string;
}
