// Generated by https://quicktype.io

export interface InstrumentoDetailResponse {
    id:         string;
    nombre:     string;
    fecha:      string;
    referentes: Referente[];
}

export interface Referente {
    codReferente: string;
    descripcion:  string;
}
