// Generated by https://quicktype.io

export interface ReferenteListResponse {
    content:       AllReferenteDTO[];
    size:          number;
    totalElements: number;
    pageNumber:    number;
    first:         boolean;
    last:          boolean;
}

export interface AllReferenteDTO {
    codReferente: string;
    descripcion:  string;
}
