// Generated by https://quicktype.io

export interface UserResponse {
    id:              null;
    username:        string;
    nombre:          string;
    apellidos:       string;
    rol:             null;
    password:        string;
    fechaNacimiento: null;
}
